name: CI - .NET (Build, Test, Publish)

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Run tests (Release)
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish artifact (project-specific)
        if: success()
        run: |
          dotnet publish ./src/ApiCepTestes_GitActions/ApiCepTestes_GitActions.csproj -c Release -f net10.0 -o ./artifacts/ApiCepTestes_GitActions
          cd ./artifacts

          zip -r ApiCepTestes_GitActions-artifact.zip ApiCepTestes_GitActions
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: viacep-published
          path: ./artifacts/ApiCepTestes_GitActions-artifact.zip
